resources:
  - name: gitResource1
    type: GitRepo
    configuration:
      gitProvider: vijay_github
      path: vijayreddy1991/jfrogtesting
#       files:
#         include: jfrog.yml
#         exclude:   
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    version:
      sha: master  
      
pipelines:
  - name: pipeline_vijay
    steps:
#       - name: java
#         type: Bash
#         configuration:
#           nodePool: vijay_u16node        
#           inputResources:
#             - name: gitResource1
#         execution:
#           onExecute:
#             - printenv            
      - name: testing
        type: Bash
        execution:
          onExecute:
            - sudo --version
            - wget --version
            - curl --version
            
            - gradle --version
        configuration:
          inputResources:
            - name: gitResource1        
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
                autoPull: true
      
