resources:
  - name: gitResource1
    type: GitRepo
    configuration:
      gitProvider: vijay_github
      path: vijayreddy1991/u18java
#       files:
#         only: README|install.sh|node
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    version:
      sha: master
      
pipelines:
  - name: pipeline_vijay
    steps:
      - name: java
        type: Bash
        configuration:
          inputResources:
            - name: gitResource1
        execution:
          onExecute:
            - printenv
            - pushd $res_gitResource1_resourcePath
            - docker build -t=u18java:dev .
      - name: testing
        type: Bash
        execution:
          onExecute:
            - _set_jdk openjdk8
            - java --version
            - _set_jdk openjdk8
            - java --version
            - echo $JAVA_HOME
            - echo $PATH
        configuration:
          inputSteps:
            - name: java
          runtime:
            type: image
            image:
              custom:
                name: vijayreddy1991/u18java
                tag: dev
                autoPull: false
      
