pipelines:
  - name: pipe1
    steps:
      - name: test_step_1
        type: bash
        configuration: 
          priority: 1
        execution:
          onExecute:
            - echo "executing task command 1"
 bhkghuoeq  k;ml
