resources:
  - name: gitResource1
    type: GitRepo
    configuration:
      gitProvider: vijay_github
      path: vijayreddy1991/jfrogtesting
#       files:
#         include: jfrog.yml
# #         exclude:   
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    version:
      sha: master  
      
pipelines:
  - name: pipeline_vijay
    steps:
      - name: java
        type: Bash
        configuration:
#           nodePool: vijay_node        
          runtime:
            type: image
            image:
#               auto:
#                 language: java
#                 versions:            
              custom:
                name: drydock/u18java
                tag: master
                autoPull: true      
          inputResources:
            - name: gitResource1
        execution:
          onExecute:
            - printenv 
            - java -version
            - _set_jdk openjdk8
            - java -version
            - echo $JAVA_HOME
            - echo $PATH
            - _set_jdk openjdk11
            - java -version
            - echo $JAVA_HOME
            - echo $PATH
            - mvn --version
            - ant -version
      - name: go
        type: Bash
        configuration:
#           nodePool: vijay_node           
          inputSteps:
            - name: java      
          runtime:
            type: image
            image:
#               auto:
#                 language: go
#                 versions:            
              custom:
                name: drydock/u18go
                tag: master
                autoPull: true
        execution:
          onExecute:
            - source /root/.gvm/scripts/gvm
            - gvm list
            - go version
            - gvm use 1.11.10 
            - go version
            - gvm use 1.12.5
            - go version                
      - name: cpp
        type: Bash
        configuration:
#           nodePool: vijay_node           
          inputSteps:
            - name: go      
          runtime:
            type: image
            image:
#               auto:
#                 language: c
#                 versions:            
              custom:
                name: drydock/u18cpp
                tag: master
                autoPull: true
        execution:
          onExecute:
            - gcc --version
            - clang --version
            
            
      
